[pytest]
asyncio_default_fixture_loop_scope = function
env =
    D:CSMS_TRIGGER_ADDRESS=http://localhost:5001
    D:CSMS_ADDRESS=wss://localhost:9000
    D:BASIC_AUTH_CP=CP-001
    D:BASIC_AUTH_CP_A=CP_A_SP1
    D:BASIC_AUTH_CP_B=CP_B
    D:BASIC_AUTH_CP_C=CP_C
    D:BASIC_AUTH_CP_D=CP_D
    D:BASIC_AUTH_CP_E=CP_E
    D:BASIC_AUTH_CP_F=CP_F
    D:BASIC_AUTH_CP_G=CP_G
    D:BASIC_AUTH_CP_PASSWORD=test1234
    D:INVALID_ID_TOKEN=100000C02
    D:INVALID_ID_TOKEN_TYPE=Cash
    D:BLOCKED_ID_TOKEN=100000C06
    D:BLOCKED_ID_TOKEN_TYPE=Central
    D:EXPIRED_ID_TOKEN=100000C07
    D:EXPIRED_ID_TOKEN_TYPE=Central
    D:TLS_CA_CERT=/home/aviran/Projects/start-fueling/tzi-octt/certs/ca.pem
    D:TLS_CLIENT_CERT=/home/aviran/Projects/start-fueling/tzi-octt/certs/client.pem
    D:TLS_CLIENT_KEY=/home/aviran/Projects/start-fueling/tzi-octt/certs/client.key
    D:TLS_INVALID_CLIENT_CERT=/home/aviran/Projects/start-fueling/tzi-octt/certs/invalid_client.pem
    D:TLS_INVALID_CLIENT_KEY=/home/aviran/Projects/start-fueling/tzi-octt/certs/invalid_client.key
    D:SECURITY_PROFILE_2_CP=CP_1
    D:SECURITY_PROFILE_2_CP_A=CP_A_SP2
    D:SECURITY_PROFILE_3_CP=CP-004
    D:SECURITY_PROFILE_3_CP_A=CP_A_SP3
    D:NEW_BASIC_AUTH_PASSWORD=new_password_12345678
    D:CSMS_ACTION_TIMEOUT=30
    D:CONFIGURED_EVSE_ID=1
    D:CONFIGURED_CONNECTOR_ID=1
    D:CONFIGURED_CP_MODEL=CP Model 1.0
    D:CONFIGURED_CP_VENDOR=tzi.app
    D:VALID_ID_TOKEN=TAG-001
    D:VALID_ID_TOKEN_TYPE=ISO14443
    D:VALID_IDTOKEN_IDTOKEN=100000C01
    D:VALID_IDTOKEN_TYPE=Central
    D:VALID_ID_TOKEN_2=100000C39B
    D:VALID_ID_TOKEN_TYPE_2=Central
    D:GROUP_ID=GROUP001
    D:MASTERPASS_ID_TOKEN=MASTERC47
    D:MASTERPASS_ID_TOKEN_TYPE=Central
    D:MASTERPASS_GROUP_ID=GROUP001
    D:ISO15118_CERT_HASH_DATA_FILE=certs/iso15118_cert_hash_data.json
    D:ISO15118_REVOKED_CERT_HASH_DATA_FILE=certs/iso15118_revoked_cert_hash_data.json
    D:CONTRACT_CERT_FILE=certs/contract_cert.pem
    D:CONTRACT_CERT_EMAID=DE-TZI-C12345-A
    D:LOCAL_LIST_VERSION=1
    D:LOCAL_AUTH_LIST_ID_TOKEN=D001001
    D:LOCAL_AUTH_LIST_ID_TOKEN_TYPE=Central
    D:LOCAL_AUTH_LIST_ID_TOKEN_2=D001002
    D:LOCAL_AUTH_LIST_ID_TOKEN_TYPE_2=Central
    D:TRANSACTION_DURATION=5
    D:SAMPLED_METER_VALUES_INTERVAL=1
    D:CLOCK_ALIGNED_METER_VALUES_INTERVAL=1
    D:TX_ENDED_METER_VALUES_INTERVAL=1
    D:CONFIGURED_CONFIGURATION_SLOT=1
    D:CONFIGURED_MESSAGE_TIMEOUT=30
    D:CONFIGURED_OCPP_CSMS_URL=wss://localhost:8082
    D:CONFIGURED_OCPP_INTERFACE=Wired0
    D:CONFIGURED_SECURITY_PROFILE=2
    D:CONFIGURED_NUMBER_PHASES=3
    D:CONFIGURED_NUMBER_OF_EVSES=1
    D:CONFIGURED_CONNECTOR_TYPE=cType2
    D:CONFIGURED_VENDOR_ID=tzi.app
    D:CONFIGURED_MESSAGE_ID=TestMessage
