[pytest]
asyncio_default_fixture_loop_scope = function
env =
    D:CSMS_TRIGGER_ADDRESS=http://localhost:5001
    D:CSMS_ADDRESS=wss://localhost:9000
    D:CP16_SP1=CP16_SP1
    D:CP16_SP3=CP16_SP3
    D:CP201_SP1=CP201_SP1
    D:CP201_SP2=CP202_SP2
    D:CP201_SP3=CP202_SP3

    D:BASIC_AUTH_CP_PASSWORD=test1234
    D:INVALID_ID_TOKEN=100000C02
    D:INVALID_ID_TOKEN_TYPE=Cash
    D:BLOCKED_ID_TOKEN=100000C06
    D:BLOCKED_ID_TOKEN_TYPE=Central
    D:EXPIRED_ID_TOKEN=100000C07
    D:EXPIRED_ID_TOKEN_TYPE=Central
    D:TLS_CA_CERT=/home/aviran/Projects/start-fueling/tzi-octt/certs/ca.pem
    D:TLS_CLIENT_CERT=/home/aviran/Projects/start-fueling/tzi-octt/certs/client.pem
    D:TLS_CLIENT_KEY=/home/aviran/Projects/start-fueling/tzi-octt/certs/client.key
    D:TLS_INVALID_CLIENT_CERT=/home/aviran/Projects/start-fueling/tzi-octt/certs/invalid_client.pem
    D:TLS_INVALID_CLIENT_KEY=/home/aviran/Projects/start-fueling/tzi-octt/certs/invalid_client.key
    D:CSMS_ACTION_TIMEOUT=30
    D:CONFIGURED_EVSE_ID=1
    D:CONFIGURED_CONNECTOR_ID=1
    D:VALID_ID_TOKEN=TAG-001
    D:VALID_ID_TOKEN_TYPE=ISO14443
    D:VALID_IDTOKEN_IDTOKEN=100000C01
    D:VALID_IDTOKEN_TYPE=Central
    D:VALID_ID_TOKEN_2=100000C39B
    D:VALID_ID_TOKEN_TYPE_2=Central
    D:GROUP_ID=GROUP001
    D:MASTERPASS_ID_TOKEN=MASTERC47
    D:MASTERPASS_ID_TOKEN_TYPE=Central
    D:MASTERPASS_GROUP_ID=GROUP001
    D:ISO15118_CERT_HASH_DATA_FILE=certs/iso15118_cert_hash_data.json
    D:ISO15118_REVOKED_CERT_HASH_DATA_FILE=certs/iso15118_revoked_cert_hash_data.json
    D:CONTRACT_CERT_FILE=certs/contract_cert.pem
    D:LOCAL_LIST_VERSION=1
    D:TRANSACTION_DURATION=5
    D:SAMPLED_METER_VALUES_INTERVAL=1
    D:CLOCK_ALIGNED_METER_VALUES_INTERVAL=1
    D:TX_ENDED_METER_VALUES_INTERVAL=1
    D:CONFIGURED_CONFIGURATION_SLOT=1
    D:CONFIGURED_MESSAGE_TIMEOUT=30
    D:CONFIGURED_OCPP_INTERFACE=Wired0
    D:CONFIGURED_SECURITY_PROFILE=2
    D:CONFIGURED_NUMBER_PHASES=3
    D:CONFIGURED_NUMBER_OF_EVSES=1
    D:CONFIGURED_CONNECTOR_TYPE=cType2
    D:CONFIGURED_VENDOR_ID=tzi.app
    D:CONFIGURED_MESSAGE_ID=TestMessage
